apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wu1ebdsvh-go
  janus-idp.io/tekton: wu1ebdsvh-go
  backstage.io/kubernetes-id: wu1ebdsvh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wu1ebdsvh-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
