apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wu1ebdsvh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wu1ebdsvh-go 
  name: wu1ebdsvh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wu1ebdsvh-go 
